trainer:
  epochs: 100
  freeze_extraction: True
dataloader:
  data_name: 'cifar10'
  batch_size: 128
  data_augmentation: 'minimal'
model:
  model_name: 'vgg19_cifar10'
optimizer:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0